name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: header.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          extras_css: |
            h1, h2 { color: #c9d1d9}
            svg { color: #8b949e }
          token: ${{ secrets.METRICS_TOKEN }}

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: achievements.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          extras_css: |
            h1, h2 { color: #c9d1d9}
            svg { color: #8b949e }
          base: ""
          plugin_achievements: yes
          plugin_achievements_limit: 5
          plugin_achievements_threshold: "A"
          token: ${{ secrets.METRICS_TOKEN }}
