name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: header.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          token: ${{ secrets.METRICS_TOKEN }}
  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: achievements.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          base: ""
          plugin_achievements: yes
          token: ${{ secrets.METRICS_TOKEN }}

