name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: header.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          extras_css: |
            h1, h2 {
              color: #c9d1d9
            }
          token: ${{ secrets.METRICS_TOKEN }}

  achievements:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: achievements.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          base: ""
          plugin_achievements: yes
          plugin_achievements_limit: 5
          plugin_achievements_threshold: "A"
          token: ${{ secrets.METRICS_TOKEN }}

  activity:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: activity.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          base: ""
          plugin_activity: yes
          token: ${{ secrets.METRICS_TOKEN }}

  habits:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@main
        with:
          filename: habits.svg
          config_timezone: America/Fortaleza
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes
          base: ""
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          token: ${{ secrets.METRICS_TOKEN }}
